image: docker:19.03.8
services:
    - docker:19.03.8-dind

stages:
    - environment
    - build
    - test
    - deploy

variables:
    CONTAINER_ENV: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    CONTAINER_TAG: $CI_REGISTRY_IMAGE:latest 

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

create container:
    stage: environment
    script:
        - docker pull $CONTAINER_TAG || true
        - docker build --cache-from $CONTAINER_TAG --tag $CONTAINER_ENV .
        - docker push $CONTAINER_ENV

build:
    stage: build
    script:
        - docker pull $CONTAINER_ENV
        - docker run --rm -v $(pwd):/root/project -w /root/project
            $CONTAINER_ENV
            make

unit test:
    stage: test
    script:
        - docker pull $CONTAINER_ENV
        - docker run --rm -v $(pwd):/root/project -w /root/project
            $CONTAINER_ENV
            make test
        - CMOCKA_XML_FILE=%g.xml CMOCKA_MESSAGE_OUTPUT=xml ./build/Test
    artifacts:
        reports:
            junit: ./*.xml
        expire_in: 1 day

coverage:
    stage: test
    script:
        - docker pull $CONTAINER_ENV
        - docker run --rm -v $(pwd):/root/project -w /root/project
            $CONTAINER_ENV
            make covr
        - gcovr build/test -r src --html-details -o test.html
    artifacts:
        paths: 
            - ./*.html
        expire_in: 1 day

push container:
    stage: deploy
    script:
        - docker pull $CONTAINER_ENV
        - docker tag $CONTAINER_ENV $CONTAINER_TAG
        - docker push $CONTAINER_TAG
